apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: resourcetypes.hami.pandaria.com
spec:
  group: hami.pandaria.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resourceTypes:
                  type: array
                  items:
                    type: string
  scope: Cluster
  names:
    plural: resourcetypes
    singular: resourcetype
    kind: ResourceType
    shortNames:
    - rt
