annotations:
  catalog.cattle.io/display-name: Pandaria Alerting Drivers
  catalog.cattle.io/kube-version: '>= 1.27.0-0'
  catalog.cattle.io/namespace: cattle-monitoring-system
  catalog.cattle.io/permits-os: linux,windows
  catalog.cattle.io/rancher-version: '>= 2.9.0-0 < 2.10.0-0'
  catalog.cattle.io/release-name: pandaria-alerting-drivers
  catalog.cattle.io/type: cluster-tool
apiVersion: v2
description: Pandaria alerting drivers for Prometheus
keywords:
- alert
- prometheus
name: pandaria-alerting-drivers
version: 0.0.6
