#!/bin/bash

set -euo pipefail
cd $(dirname $0)/../


# Get the folder of Aliyun OSS bucket from Git branch name.
# e.g. branch name: `dev/v2.6` -> folder name: `dev-v2.6`, branch: `release/v2.6` -> folder: `release-v2.6`
if [[ -z "${GITHUB_REF:-}" ]]; then
    echo "ERROR: this script needs to run in CI pipeline."
    exit 1
else
    echo "---- GITHUB_REF: ${GITHUB_REF}"
    echo "---- Checking git branch format"
    BRANCH=${GITHUB_REF#refs/heads/}
    if echo "${BRANCH}" | grep "dev/\|release/"; then
        echo "---- Git branch: ${BRANCH}"
    else
        echo "---- Invalid git branch format: ${BRANCH}"
        exit 1
    fi
    VERSION_FOLDER="$(echo ${BRANCH} | tr / -)"
    echo "---- VERSION_FOLDER: ${VERSION_FOLDER}"
    if [[ -z "${VERSION_FOLDER}" ]]; then
        echo "ERROR: failed to get VERSION_FOLDER"
        exit 1
    fi
fi

echo "---- Downloading ossutil"
wget -O ossutil.zip "https://gosspublic.alicdn.com/ossutil/${OSSUTIL_VERSION}/ossutil-v${OSSUTIL_VERSION}-linux-amd64.zip"
unzip ./ossutil.zip
sudo cp ./ossutil-v*/ossutil /bin/
sudo chmod 755 /bin/ossutil

echo "---- Configuring ossutil"
ossutil config -e "${ALIYUN_ENDPOINT}" -i "${ALIYUN_ACCESS_KEY_ID}" -k "${ALIYUN_SECRET_ACCESS_KEY}"

echo "---- Removing existing asset files"
ossutil rm -rf "${ALIYUN_BUCKET}/${VERSION_FOLDER}/"

echo "---- Creating folders"
ossutil mkdir "${ALIYUN_BUCKET}/${VERSION_FOLDER}/assets" || echo "---- assets folder already exists" # Ensure assets folder exists
ossutil mkdir "${ALIYUN_BUCKET}/${LOGO_FOLDER}/" || echo "---- logo folder already exists" # Ensure LOGO folder exists

echo "---- Copy asset files"
ossutil cp -rf "./assets" "${ALIYUN_BUCKET}/${VERSION_FOLDER}/assets/"
ossutil cp -f "./index.yaml" "${ALIYUN_BUCKET}/${VERSION_FOLDER}/"

echo "---- Copy LOGO files"
ossutil cp -rf "./assets/logo" "${ALIYUN_BUCKET}/${LOGO_FOLDER}/"

echo '---- Set ACL for file'
ossutil set-acl ${ALIYUN_BUCKET}/${VERSION_FOLDER} ${VERSION_FOLDER_ACCESS} -rf
ossutil set-acl ${ALIYUN_BUCKET}/${LOGO_FOLDER} ${LOGO_FOLDER_ACCESS} -rf
