apiVersion: "hami.pandaria.com/v1"
kind: ResourceType
metadata:
  name: rancher-hami-resourcetypes
  labels:
    hami.pandaria.com/installed-by-chart: "true"
spec:
  resourceTypes:
    - {{ .Values.resourceName }}
    - {{ .Values.resourceMem }}
    - {{ .Values.resourceCores }}
    - {{ .Values.resourceMemPercentage }}
    - {{ .Values.resourcePriority }}
    - {{ .Values.mluResourceName }}
    - {{ .Values.mluResourceMem }}
    - {{ .Values.mluResourceCores }}
    - {{ .Values.dcuResourceName }}
    - {{ .Values.dcuResourceMem }}
    - {{ .Values.dcuResourceCores }}
    - {{ .Values.iluvatarResourceName }}
    - {{ .Values.iluvatarResourceMem }}
    - {{ .Values.iluvatarResourceCore }}
    {{- if .Values.devices.ascend.enabled }}
    {{- range .Values.devices.ascend.customresources }}
    - {{ . }}
    {{- end }}
    {{- end }}
    {{- if .Values.devices.mthreads.enabled }}
    {{- range .Values.devices.mthreads.customresources }}
    - {{ . }}
    {{- end }}
    {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rancher-hami-resourcetypes-view-role
rules:
- apiGroups: ["hami.pandaria.com"]
  resources: ["resourcetypes"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-hami-resourcetypes-view-role-binding
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: rancher-hami-resourcetypes-view-role
  apiGroup: rbac.authorization.k8s.io
