sharedeviceplugin:
  image:
    repository: cnrancher/gpu-device-plugin
    tag: "v0.1.3"
defaultScheduler:
  version: "v1.30"
  supportedVersions:
    v1.27:
      repository: "rancher/hyperkube"
      tag: "v1.27.11-rancher1"
    v1.28:
      repository: "rancher/hyperkube"
      tag: "v1.28.7-rancher1"
    v1.29:
      repository: "rancher/hyperkube"
      tag: "v1.29.7-rancher1"
    v1.30:
      repository: "rancher/hyperkube"
      tag: "v1.30.3-rancher1"
schedulerextender:
  image:
    repository: cnrancher/gpu-scheduler-extender
    tag: "v0.1.3"
  schedulerName: rancher-gpushare-scheduler
  port: 9100
  verbose: 4
  nodeSelector: {}
  tolerations: []
  affinity: {}
# GPU Sharing Memory unit: GiB or MiB    
memoryunit: GiB
global:
  systemDefaultRegistry: ""

runtimeClassName: null
